name: Processar novos processos

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  processar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: worker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run processar:novos-processos
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          DATAJUD_API_KEY: ${{ secrets.DATAJUD_API_KEY }}
